apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-db
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-db
  template:
    metadata:
      labels:
        app: appointment-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: APPOINTMENT_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediconnect-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: appointment-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: appointment-db-storage
          persistentVolumeClaim:
            claimName: appointment-db-pvc
