apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-db-pvc
  namespace: mediconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-db
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-db
  template:
    metadata:
      labels:
        app: doctor-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: DOCTOR_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediconnect-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: doctor-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: doctor-db-storage
          persistentVolumeClaim:
            claimName: doctor-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-db
  namespace: mediconnect
spec:
  selector:
    app: doctor-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
