// Doctor IDs must match the _id values in the frontend assets/data.js
// Time slots must match the format generated by useAppointment hook: "9:00 AM", "10:00 AM" etc.
// The hook generates slots every 30 minutes from 10:00 AM to 9:00 PM

export const mockDoctors = [
  {
    id: "doc1",
    name: "Dr. Richard James",
    specialty: "General physician",
    consultationFee: 2500,
    availableSlots: [
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "12:00 PM", "12:30 PM", "01:00 PM", "01:30 PM",
      "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM",
      "04:00 PM", "04:30 PM", "05:00 PM"
    ]
  },
  {
    id: "doc2",
    name: "Dr. Emily Larson",
    specialty: "Gynecologist",
    consultationFee: 3000,
    availableSlots: [
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "12:00 PM", "12:30 PM", "01:00 PM", "01:30 PM",
      "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM"
    ]
  },
  {
    id: "doc3",
    name: "Dr. Sarah Patel",
    specialty: "Dermatologist",
    consultationFee: 2800,
    availableSlots: [
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "12:00 PM", "12:30 PM", "01:00 PM", "01:30 PM",
      "02:00 PM", "02:30 PM"
    ]
  },
  {
    id: "doc4",
    name: "Dr. Christopher Lee",
    specialty: "Pediatricians",
    consultationFee: 2000,
    availableSlots: [
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "01:00 PM", "01:30 PM", "02:00 PM", "02:30 PM",
      "03:00 PM", "03:30 PM", "04:00 PM"
    ]
  },
  {
    id: "doc5",
    name: "Dr. Jennifer Garcia",
    specialty: "Neurologist",
    consultationFee: 3500,
    availableSlots: [
      "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM",
      "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM"
    ]
  }
];
