apiVersion: v1
kind: Secret
metadata:
  name: mediconnect-secrets
  namespace: mediconnect
type: Opaque
stringData:
  # Database credentials
  DB_PASSWORD: "postgres123"

  # PayHere credentials (replace with real sandbox values)
  PAYHERE_MERCHANT_ID: "1235163"
  PAYHERE_MERCHANT_SECRET: "ODEwOTA3NTU5NzQ1OTYyMTkwOTI1NzMyNzAwMjU3NDE3ODgwOA=="
