apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: mediconnect-patient-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: PATIENT_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: PATIENT_DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediconnect-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mediconnect-secrets
                  key: JWT_SECRET
            - name: INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: mediconnect-secrets
                  key: INTERNAL_SECRET
