apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: YOUR_DOCKERHUB_USERNAME/mediconnect-api-gateway:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: APPOINTMENT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mediconnect-config
                  key: PAYMENT_SERVICE_URL
